
package ru.rbt.jetski.advanta.ws.apiprojects;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APIProjectsHttpPost", targetNamespace = "http://streamline/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APIProjectsHttpPost {


    /**
     * 
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ProjectWrapper
     */
    @WebMethod(operationName = "GetProjectInfo")
    @WebResult(name = "ProjectWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public ProjectWrapper getProjectInfo(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param name
     * @param description
     * @param projectId
     * @param status
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateProjectInfo")
    @WebResult(name = "string", targetNamespace = "http://streamline/", partName = "Body")
    public String updateProjectInfo(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "name")
                    String name,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "description")
                    String description,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "status")
                    String status);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectFieldWrapper
     */
    @WebMethod(operationName = "GetProjectFields")
    @WebResult(name = "ArrayOfProjectFieldWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public ArrayOfProjectFieldWrapper getProjectFields(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

    /**
     *
     * @param parentProjectId
     * @param aspnetSessionId
     * @param typeId
     * @param status
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "GetProjectsUidsByType")
    @WebResult(name = "ArrayOfProjectWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public ArrayOfProjectWrapper getProjectsUidsByType(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "typeId")
                    String typeId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "status")
                    String status,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentProjectId")
                    String parentProjectId);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "GetSubprojectsDates")
    @WebResult(name = "ArrayOfProjectWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public ArrayOfProjectWrapper getSubprojectsDates(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfResourceAssignmentWrapper
     */
    @WebMethod(operationName = "GetProjectResourceAssignments")
    @WebResult(name = "ArrayOfResourceAssignmentWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public ArrayOfResourceAssignmentWrapper getProjectResourceAssignments(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfRelationdWrapper
     */
    @WebMethod(operationName = "GetHorizontalRelationsProjects")
    @WebResult(name = "ArrayOfRelationdWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public ArrayOfRelationdWrapper getHorizontalRelationsProjects(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

}
