
package ru.rbt.jetski.advanta.ws.apiprojects;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APIProjectsSoap", targetNamespace = "http://streamline/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APIProjectsSoap {


    /**
     * 
     * @param project
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfPersonsGroupWrapper
     */
    @WebMethod(operationName = "GetGroupsWithPersonsIdsAllowedToWriteDiscussion", action = "http://streamline/GetGroupsWithPersonsIdsAllowedToWriteDiscussion")
    @WebResult(name = "GetGroupsWithPersonsIdsAllowedToWriteDiscussionResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetGroupsWithPersonsIdsAllowedToWriteDiscussion", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetGroupsWithPersonsIdsAllowedToWriteDiscussion")
    @ResponseWrapper(localName = "GetGroupsWithPersonsIdsAllowedToWriteDiscussionResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetGroupsWithPersonsIdsAllowedToWriteDiscussionResponse")
    public ArrayOfPersonsGroupWrapper getGroupsWithPersonsIdsAllowedToWriteDiscussion(
            @WebParam(name = "project", targetNamespace = "http://streamline/")
                    GetGroupsWithPersonsIdsAllowedToWriteDiscussionDataContract project);

    /**
     *
     * @param newProject
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateProject", action = "http://streamline/CreateProject")
    @WebResult(name = "CreateProjectResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "CreateProject", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.CreateProject")
    @ResponseWrapper(localName = "CreateProjectResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.CreateProjectResponse")
    public String createProject(
            @WebParam(name = "newProject", targetNamespace = "http://streamline/")
                    CreateProjectDataContract newProject);

    /**
     *
     * @param newProject
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateProjectByDiscussion", action = "http://streamline/CreateProjectByDiscussion")
    @WebResult(name = "CreateProjectByDiscussionResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "CreateProjectByDiscussion", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.CreateProjectByDiscussion")
    @ResponseWrapper(localName = "CreateProjectByDiscussionResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.CreateProjectByDiscussionResponse")
    public String createProjectByDiscussion(
            @WebParam(name = "newProject", targetNamespace = "http://streamline/")
                    CreateProjectWithDiscussion newProject);

    /**
     *
     * @param projectData
     */
    @WebMethod(operationName = "DelegateProject", action = "http://streamline/DelegateProject")
    @RequestWrapper(localName = "DelegateProject", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.DelegateProject")
    @ResponseWrapper(localName = "DelegateProjectResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.DelegateProjectResponse")
    public void delegateProject(
            @WebParam(name = "projectData", targetNamespace = "http://streamline/")
                    DelegateProjectDataContract projectData);

    /**
     *
     * @param contract
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeParent", action = "http://streamline/ChangeParent")
    @WebResult(name = "ChangeParentResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "ChangeParent", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ChangeParent")
    @ResponseWrapper(localName = "ChangeParentResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ChangeParentResponse")
    public String changeParent(
            @WebParam(name = "contract", targetNamespace = "http://streamline/")
                    ChangeParentDataContract contract);

    /**
     *
     * @param project
     */
    @WebMethod(operationName = "DeleteProject", action = "http://streamline/DeleteProject")
    @RequestWrapper(localName = "DeleteProject", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.DeleteProject")
    @ResponseWrapper(localName = "DeleteProjectResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.DeleteProjectResponse")
    public void deleteProject(
            @WebParam(name = "project", targetNamespace = "http://streamline/")
                    ProjectIdDataContract project);

    /**
     *
     * @param contract
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ProjectWrapper
     */
    @WebMethod(operationName = "GetProject", action = "http://streamline/GetProject")
    @WebResult(name = "GetProjectResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProject", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProject")
    @ResponseWrapper(localName = "GetProjectResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectResponse")
    public ProjectWrapper getProject(
            @WebParam(name = "contract", targetNamespace = "http://streamline/")
                    ProjectIdDataContract contract);

    /**
     *
     * @param contract
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateProject", action = "http://streamline/UpdateProject")
    @WebResult(name = "UpdateProjectResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "UpdateProject", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.UpdateProject")
    @ResponseWrapper(localName = "UpdateProjectResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.UpdateProjectResponse")
    public String updateProject(
            @WebParam(name = "contract", targetNamespace = "http://streamline/")
                    UpdateProjectDataContract contract);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ProjectWrapper
     */
    @WebMethod(operationName = "GetProjectInfo", action = "http://streamline/GetProjectInfo")
    @WebResult(name = "GetProjectInfoResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProjectInfo", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectInfo")
    @ResponseWrapper(localName = "GetProjectInfoResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectInfoResponse")
    public ProjectWrapper getProjectInfo(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param name
     * @param description
     * @param projectId
     * @param status
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateProjectInfo", action = "http://streamline/UpdateProjectInfo")
    @WebResult(name = "UpdateProjectInfoResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "UpdateProjectInfo", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.UpdateProjectInfo")
    @ResponseWrapper(localName = "UpdateProjectInfoResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.UpdateProjectInfoResponse")
    public String updateProjectInfo(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId,
            @WebParam(name = "name", targetNamespace = "http://streamline/")
                    String name,
            @WebParam(name = "description", targetNamespace = "http://streamline/")
                    String description,
            @WebParam(name = "status", targetNamespace = "http://streamline/")
                    String status);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectFieldWrapper
     */
    @WebMethod(operationName = "GetProjectFields", action = "http://streamline/GetProjectFields")
    @WebResult(name = "GetProjectFieldsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProjectFields", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectFields")
    @ResponseWrapper(localName = "GetProjectFieldsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectFieldsResponse")
    public ArrayOfProjectFieldWrapper getProjectFields(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param lstParams
     * @param projectId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateProjectFields", action = "http://streamline/UpdateProjectFields")
    @WebResult(name = "UpdateProjectFieldsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "UpdateProjectFields", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.UpdateProjectFields")
    @ResponseWrapper(localName = "UpdateProjectFieldsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.UpdateProjectFieldsResponse")
    public String updateProjectFields(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId,
            @WebParam(name = "lstParams", targetNamespace = "http://streamline/")
                    ArrayOfFieldWrapper lstParams);

    /**
     *
     * @param contract
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectChildWrapper
     */
    @WebMethod(operationName = "GetProjectChilds", action = "http://streamline/GetProjectChilds")
    @WebResult(name = "GetProjectChildsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProjectChilds", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectChilds")
    @ResponseWrapper(localName = "GetProjectChildsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectChildsResponse")
    public ArrayOfProjectChildWrapper getProjectChilds(
            @WebParam(name = "contract", targetNamespace = "http://streamline/")
                    GetProjectChildsDataContract contract);

    /**
     *
     * @param parentProjectId
     * @param aspnetSessionId
     * @param typeId
     * @param status
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "GetProjectsUidsByType", action = "http://streamline/GetProjectsUidsByType")
    @WebResult(name = "GetProjectsUidsByTypeResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProjectsUidsByType", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectsUidsByType")
    @ResponseWrapper(localName = "GetProjectsUidsByTypeResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectsUidsByTypeResponse")
    public ArrayOfProjectWrapper getProjectsUidsByType(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "typeId", targetNamespace = "http://streamline/")
                    String typeId,
            @WebParam(name = "status", targetNamespace = "http://streamline/")
                    String status,
            @WebParam(name = "parentProjectId", targetNamespace = "http://streamline/")
                    String parentProjectId);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "GetSubprojectsDates", action = "http://streamline/GetSubprojectsDates")
    @WebResult(name = "GetSubprojectsDatesResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetSubprojectsDates", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetSubprojectsDates")
    @ResponseWrapper(localName = "GetSubprojectsDatesResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetSubprojectsDatesResponse")
    public ArrayOfProjectWrapper getSubprojectsDates(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfResourceAssignmentWrapper
     */
    @WebMethod(operationName = "GetProjectResourceAssignments", action = "http://streamline/GetProjectResourceAssignments")
    @WebResult(name = "GetProjectResourceAssignmentsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProjectResourceAssignments", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectResourceAssignments")
    @ResponseWrapper(localName = "GetProjectResourceAssignmentsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectResourceAssignmentsResponse")
    public ArrayOfResourceAssignmentWrapper getProjectResourceAssignments(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId);

    /**
     *
     * @param sortWrappers
     * @param hierarchical
     * @param aspnetSessionId
     * @param filterWrappers
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "GetProjects", action = "http://streamline/GetProjects")
    @WebResult(name = "GetProjectsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetProjects", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjects")
    @ResponseWrapper(localName = "GetProjectsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetProjectsResponse")
    public ArrayOfProjectWrapper getProjects(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "filterWrappers", targetNamespace = "http://streamline/")
                    ArrayOfFilterWrapper filterWrappers,
            @WebParam(name = "sortWrappers", targetNamespace = "http://streamline/")
                    ArrayOfSortWrapper sortWrappers,
            @WebParam(name = "Hierarchical", targetNamespace = "http://streamline/")
                    boolean hierarchical);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.ArrayOfRelationdWrapper
     */
    @WebMethod(operationName = "GetHorizontalRelationsProjects", action = "http://streamline/GetHorizontalRelationsProjects")
    @WebResult(name = "GetHorizontalRelationsProjectsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetHorizontalRelationsProjects", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetHorizontalRelationsProjects")
    @ResponseWrapper(localName = "GetHorizontalRelationsProjectsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiprojects.GetHorizontalRelationsProjectsResponse")
    public ArrayOfRelationdWrapper getHorizontalRelationsProjects(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "projectId", targetNamespace = "http://streamline/")
                    String projectId);

}
