
package ru.rbt.jetski.advanta.ws.apiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APIServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APIServiceHttpPost {


    /**
     * 
     * @param aspnetSessionId
     * @param directoryId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.RecordsListWrapper
     */
    @WebMethod(operationName = "GetRecords")
    @WebResult(name = "RecordsListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RecordsListWrapper getRecords(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryId")
                    String directoryId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

    /**
     *
     * @param classifierId
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.DirectoriesListWrapper
     */
    @WebMethod(operationName = "GetUsedObjectsByClassifier")
    @WebResult(name = "DirectoriesListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public DirectoriesListWrapper getUsedObjectsByClassifier(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "classifierId")
                    String classifierId);

    /**
     *
     * @param classifierId
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.DirectoriesListWrapper
     */
    @WebMethod(operationName = "GetUsedTemplatesForClassifier")
    @WebResult(name = "DirectoriesListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public DirectoriesListWrapper getUsedTemplatesForClassifier(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "classifierId")
                    String classifierId);

    /**
     *
     * @param directoryGroupId
     * @param childDirectoryId
     * @param aspnetSessionId
     * @param parentdirectoryRecordId
     * @param projectId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.RecordsListWrapper
     */
    @WebMethod(operationName = "GetChildRecords")
    @WebResult(name = "RecordsListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RecordsListWrapper getChildRecords(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryGroupId")
                    String directoryGroupId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentdirectoryRecordId")
                    String parentdirectoryRecordId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childDirectoryId")
                    String childDirectoryId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId);

    /**
     *
     * @param aspnetSessionId
     * @param directoryTemplateId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.DirectoryInfoWrapper
     */
    @WebMethod(operationName = "GetDirectoryInfo")
    @WebResult(name = "DirectoryInfoWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public DirectoryInfoWrapper getDirectoryInfo(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryTemplateId")
                    String directoryTemplateId);

    /**
     *
     * @param directoryRecordId
     * @param aspnetSessionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteDirectoryRecord")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String deleteDirectoryRecord(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryRecordId")
                    String directoryRecordId);

    /**
     *
     * @param recordStatus
     * @param directoryRecordId
     * @param aspnetSessionId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeDirectoryRecordStatus")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String changeDirectoryRecordStatus(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryRecordId")
                    String directoryRecordId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "RecordStatus")
                    String recordStatus);

    /**
     *
     * @param recordStatus
     * @param aspnetSessionId
     * @param directoryId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "SearchDirectoryRecordsByStatus")
    @WebResult(name = "ArrayOfProjectWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfProjectWrapper searchDirectoryRecordsByStatus(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryId")
                    String directoryId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "RecordStatus")
                    String recordStatus);

    /**
     *
     * @param aspnetSessionId
     * @param directoryId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.DirectoryInfoWrapper
     */
    @WebMethod(operationName = "GetDirectoryRequisites")
    @WebResult(name = "DirectoryInfoWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public DirectoryInfoWrapper getDirectoryRequisites(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryId")
                    String directoryId);

    /**
     *
     * @param aspnetSessionId
     * @param type
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.DirectoriesListWrapper
     */
    @WebMethod(operationName = "GetDirectoriesList")
    @WebResult(name = "DirectoriesListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public DirectoriesListWrapper getDirectoriesList(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "type")
                    String type);

    /**
     *
     * @param classifierId
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.RecordsListWrapper
     */
    @WebMethod(operationName = "GetClassifierRecords")
    @WebResult(name = "RecordsListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RecordsListWrapper getClassifierRecords(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "classifierId")
                    String classifierId);

    /**
     *
     * @param aspnetSessionId
     * @param directoryID
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.RelationObjectsListWrapper
     */
    @WebMethod(operationName = "GetRelationObjects")
    @WebResult(name = "RelationObjectsListWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public RelationObjectsListWrapper getRelationObjects(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DirectoryID")
                    String directoryID);

    /**
     *
     * @param aspnetSessionId
     * @param projectId
     * @param relationTemplateID
     * @param directoryRecordObjectID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertObjectToProjectRelation")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String insertObjectToProjectRelation(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryRecordObjectID")
                    String directoryRecordObjectID,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "projectId")
                    String projectId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "relationTemplateID")
                    String relationTemplateID);

    /**
     *
     * @param aspnetSessionId
     * @param directoryId
     * @param fieldValue
     * @param fieldId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.ArrayOfProjectWrapper
     */
    @WebMethod(operationName = "SearchDirectoryRecordValues")
    @WebResult(name = "ArrayOfProjectWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfProjectWrapper searchDirectoryRecordValues(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "directoryId")
                    String directoryId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fieldId")
                    String fieldId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fieldValue")
                    String fieldValue);

    /**
     *
     * @param aspnetSessionId
     * @param documentId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiservice.ArrayOfDocumentVersionWrapper
     */
    @WebMethod(operationName = "GetDocumentVersions")
    @WebResult(name = "ArrayOfDocumentVersionWrapper", targetNamespace = "http://tempuri.org/", partName = "Body")
    public ArrayOfDocumentVersionWrapper getDocumentVersions(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "documentId")
                    String documentId);

}
