
package ru.rbt.jetski.advanta.ws.apiservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "APIService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://rbtn.a2nta.ru/components/services/APIService.asmx?WSDL")
public class APIService
    extends Service
{

    private final static URL APISERVICE_WSDL_LOCATION;
    private final static WebServiceException APISERVICE_EXCEPTION;
    private final static QName APISERVICE_QNAME = new QName("http://tempuri.org/", "APIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://rbtn.a2nta.ru/components/services/APIService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APISERVICE_WSDL_LOCATION = url;
        APISERVICE_EXCEPTION = e;
    }

    public APIService() {
        super(__getWsdlLocation(), APISERVICE_QNAME);
    }

    public APIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APISERVICE_QNAME, features);
    }

    public APIService(URL wsdlLocation) {
        super(wsdlLocation, APISERVICE_QNAME);
    }

    public APIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APISERVICE_QNAME, features);
    }

    public APIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns APIServiceSoap
     */
    @WebEndpoint(name = "APIServiceSoap")
    public APIServiceSoap getAPIServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "APIServiceSoap"), APIServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIServiceSoap
     */
    @WebEndpoint(name = "APIServiceSoap")
    public APIServiceSoap getAPIServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "APIServiceSoap"), APIServiceSoap.class, features);
    }

    /**
     *
     * @return
     *     returns APIServiceSoap
     */
    @WebEndpoint(name = "APIServiceSoap12")
    public APIServiceSoap getAPIServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "APIServiceSoap12"), APIServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIServiceSoap
     */
    @WebEndpoint(name = "APIServiceSoap12")
    public APIServiceSoap getAPIServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "APIServiceSoap12"), APIServiceSoap.class, features);
    }

    /**
     *
     * @return
     *     returns APIServiceHttpPost
     */
    @WebEndpoint(name = "APIServiceHttpPost")
    public APIServiceHttpPost getAPIServiceHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "APIServiceHttpPost"), APIServiceHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIServiceHttpPost
     */
    @WebEndpoint(name = "APIServiceHttpPost")
    public APIServiceHttpPost getAPIServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "APIServiceHttpPost"), APIServiceHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APISERVICE_EXCEPTION!= null) {
            throw APISERVICE_EXCEPTION;
        }
        return APISERVICE_WSDL_LOCATION;
    }

}
