
package ru.rbt.jetski.advanta.ws.apiplans;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "APIPlans", targetNamespace = "http://streamline/", wsdlLocation = "https://rbtn.a2nta.ru/components/services/APIPlans.asmx?WSDL")
public class APIPlans
    extends Service
{

    private final static URL APIPLANS_WSDL_LOCATION;
    private final static WebServiceException APIPLANS_EXCEPTION;
    private final static QName APIPLANS_QNAME = new QName("http://streamline/", "APIPlans");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://rbtn.a2nta.ru/components/services/APIPlans.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APIPLANS_WSDL_LOCATION = url;
        APIPLANS_EXCEPTION = e;
    }

    public APIPlans() {
        super(__getWsdlLocation(), APIPLANS_QNAME);
    }

    public APIPlans(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIPLANS_QNAME, features);
    }

    public APIPlans(URL wsdlLocation) {
        super(wsdlLocation, APIPLANS_QNAME);
    }

    public APIPlans(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIPLANS_QNAME, features);
    }

    public APIPlans(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APIPlans(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns APIPlansSoap
     */
    @WebEndpoint(name = "APIPlansSoap")
    public APIPlansSoap getAPIPlansSoap() {
        return super.getPort(new QName("http://streamline/", "APIPlansSoap"), APIPlansSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIPlansSoap
     */
    @WebEndpoint(name = "APIPlansSoap")
    public APIPlansSoap getAPIPlansSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://streamline/", "APIPlansSoap"), APIPlansSoap.class, features);
    }

    /**
     *
     * @return
     *     returns APIPlansSoap
     */
    @WebEndpoint(name = "APIPlansSoap12")
    public APIPlansSoap getAPIPlansSoap12() {
        return super.getPort(new QName("http://streamline/", "APIPlansSoap12"), APIPlansSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIPlansSoap
     */
    @WebEndpoint(name = "APIPlansSoap12")
    public APIPlansSoap getAPIPlansSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://streamline/", "APIPlansSoap12"), APIPlansSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIPLANS_EXCEPTION!= null) {
            throw APIPLANS_EXCEPTION;
        }
        return APIPLANS_WSDL_LOCATION;
    }

}
