
package ru.rbt.jetski.advanta.ws.apiplans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APIPlansSoap", targetNamespace = "http://streamline/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APIPlansSoap {


    /**
     * 
     * @param contract
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.apiplans.BaselinePlanWrapper
     */
    @WebMethod(operationName = "GetBaselinePlanProject", action = "http://streamline/GetBaselinePlanProject")
    @WebResult(name = "GetBaselinePlanProjectResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetBaselinePlanProject", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiplans.GetBaselinePlanProject")
    @ResponseWrapper(localName = "GetBaselinePlanProjectResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.apiplans.GetBaselinePlanProjectResponse")
    public BaselinePlanWrapper getBaselinePlanProject(
            @WebParam(name = "contract", targetNamespace = "http://streamline/")
                    GetBaselinePlanProjectDataContract contract);

}
