
package ru.rbt.jetski.advanta.ws.persons;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonsHttpPost", targetNamespace = "http://streamline/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonsHttpPost {


    /**
     * 
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.PersonQueryResult
     */
    @WebMethod(operationName = "GetPersons")
    @WebResult(name = "PersonQueryResult", targetNamespace = "http://streamline/", partName = "Body")
    public PersonQueryResult getPersons(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId);

    /**
     *
     * @param uid
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.PersonQueryResult
     */
    @WebMethod(operationName = "GetPerson")
    @WebResult(name = "PersonQueryResult", targetNamespace = "http://streamline/", partName = "Body")
    public PersonQueryResult getPerson(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "uid")
                    String uid);

    /**
     *
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.PersonQueryResult
     */
    @WebMethod(operationName = "GetAllowedPersons")
    @WebResult(name = "PersonQueryResult", targetNamespace = "http://streamline/", partName = "Body")
    public PersonQueryResult getAllowedPersons(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId);

    /**
     *
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.GroupQueryResult
     */
    @WebMethod(operationName = "GetGroups")
    @WebResult(name = "GroupQueryResult", targetNamespace = "http://streamline/", partName = "Body")
    public GroupQueryResult getGroups(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId);

    /**
     *
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.UsersListWrapper
     */
    @WebMethod(operationName = "GetPersonsXml")
    @WebResult(name = "UsersListWrapper", targetNamespace = "http://streamline/", partName = "Body")
    public UsersListWrapper getPersonsXml(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId);

    /**
     *
     * @param firstName
     * @param lastName
     * @param notes
     * @param mobilePhone
     * @param aspnetSessionId
     * @param photoBase64
     * @param company
     * @param position
     * @param businessPhone
     * @param fax
     * @param email
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "CreatePerson")
    @WebResult(name = "ServiceQueryResultOfString", targetNamespace = "http://streamline/", partName = "Body")
    public ServiceQueryResultOfString createPerson(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "firstName")
                    String firstName,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lastName")
                    String lastName,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "company")
                    String company,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "position")
                    String position,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notes")
                    String notes,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "businessPhone")
                    String businessPhone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mobilePhone")
                    String mobilePhone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fax")
                    String fax,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "email")
                    String email,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "photoBase64")
                    String photoBase64);

    /**
     *
     * @param lastName
     * @param notes
     * @param aspnetSessionId
     * @param uid
     * @param firstName
     * @param mobilePhone
     * @param photoBase64
     * @param allowLogin
     * @param company
     * @param position
     * @param businessPhone
     * @param fax
     * @param email
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "EditPerson")
    @WebResult(name = "ServiceQueryResultOfString", targetNamespace = "http://streamline/", partName = "Body")
    public ServiceQueryResultOfString editPerson(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "uid")
                    String uid,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "firstName")
                    String firstName,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lastName")
                    String lastName,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "company")
                    String company,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "position")
                    String position,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notes")
                    String notes,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "businessPhone")
                    String businessPhone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "mobilePhone")
                    String mobilePhone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fax")
                    String fax,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "email")
                    String email,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "photoBase64")
                    String photoBase64,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "allowLogin")
                    String allowLogin);

    /**
     *
     * @param aspnetSessionId
     * @param personId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "CheckUserPhoto")
    @WebResult(name = "ServiceQueryResultOfString", targetNamespace = "http://streamline/", partName = "Body")
    public ServiceQueryResultOfString checkUserPhoto(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "personId")
                    String personId);

    /**
     *
     * @param aDid
     * @param aspnetSessionId
     * @param personId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "LinkUserToAD")
    @WebResult(name = "ServiceQueryResultOfString", targetNamespace = "http://streamline/", partName = "Body")
    public ServiceQueryResultOfString linkUserToAD(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "personId")
                    String personId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ADid")
                    String aDid);

    /**
     *
     * @param aspnetSessionId
     * @param personId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "DeleteLinkWithAD")
    @WebResult(name = "ServiceQueryResultOfString", targetNamespace = "http://streamline/", partName = "Body")
    public ServiceQueryResultOfString deleteLinkWithAD(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ASPNETSessionId")
                    String aspnetSessionId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "personId")
                    String personId);

}
