
package ru.rbt.jetski.advanta.ws.persons;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonsSoap", targetNamespace = "http://streamline/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonsSoap {


    /**
     * 
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.PersonQueryResult
     */
    @WebMethod(operationName = "GetPersons", action = "http://streamline/GetPersons")
    @WebResult(name = "GetPersonsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetPersons", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetPersons")
    @ResponseWrapper(localName = "GetPersonsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetPersonsResponse")
    public PersonQueryResult getPersons(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId);

    /**
     *
     * @param uid
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.PersonQueryResult
     */
    @WebMethod(operationName = "GetPerson", action = "http://streamline/GetPerson")
    @WebResult(name = "GetPersonResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetPerson", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetPerson")
    @ResponseWrapper(localName = "GetPersonResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetPersonResponse")
    public PersonQueryResult getPerson(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "uid", targetNamespace = "http://streamline/")
                    String uid);

    /**
     *
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.PersonQueryResult
     */
    @WebMethod(operationName = "GetAllowedPersons", action = "http://streamline/GetAllowedPersons")
    @WebResult(name = "GetAllowedPersonsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetAllowedPersons", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetAllowedPersons")
    @ResponseWrapper(localName = "GetAllowedPersonsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetAllowedPersonsResponse")
    public PersonQueryResult getAllowedPersons(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId);

    /**
     *
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.GroupQueryResult
     */
    @WebMethod(operationName = "GetGroups", action = "http://streamline/GetGroups")
    @WebResult(name = "GetGroupsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetGroups", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetGroups")
    @ResponseWrapper(localName = "GetGroupsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetGroupsResponse")
    public GroupQueryResult getGroups(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId);

    /**
     *
     * @param aspnetSessionId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.UsersListWrapper
     */
    @WebMethod(operationName = "GetPersonsXml", action = "http://streamline/GetPersonsXml")
    @WebResult(name = "GetPersonsXmlResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetPersonsXml", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetPersonsXml")
    @ResponseWrapper(localName = "GetPersonsXmlResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.GetPersonsXmlResponse")
    public UsersListWrapper getPersonsXml(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId);

    /**
     *
     * @param firstName
     * @param lastName
     * @param notes
     * @param mobilePhone
     * @param aspnetSessionId
     * @param photoBase64
     * @param company
     * @param position
     * @param businessPhone
     * @param fax
     * @param email
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "CreatePerson", action = "http://streamline/CreatePerson")
    @WebResult(name = "CreatePersonResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "CreatePerson", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.CreatePerson")
    @ResponseWrapper(localName = "CreatePersonResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.CreatePersonResponse")
    public ServiceQueryResultOfString createPerson(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "firstName", targetNamespace = "http://streamline/")
                    String firstName,
            @WebParam(name = "lastName", targetNamespace = "http://streamline/")
                    String lastName,
            @WebParam(name = "company", targetNamespace = "http://streamline/")
                    String company,
            @WebParam(name = "position", targetNamespace = "http://streamline/")
                    String position,
            @WebParam(name = "notes", targetNamespace = "http://streamline/")
                    String notes,
            @WebParam(name = "businessPhone", targetNamespace = "http://streamline/")
                    String businessPhone,
            @WebParam(name = "mobilePhone", targetNamespace = "http://streamline/")
                    String mobilePhone,
            @WebParam(name = "fax", targetNamespace = "http://streamline/")
                    String fax,
            @WebParam(name = "email", targetNamespace = "http://streamline/")
                    String email,
            @WebParam(name = "photoBase64", targetNamespace = "http://streamline/")
                    String photoBase64);

    /**
     *
     * @param lastName
     * @param notes
     * @param aspnetSessionId
     * @param uid
     * @param firstName
     * @param mobilePhone
     * @param photoBase64
     * @param allowLogin
     * @param company
     * @param position
     * @param businessPhone
     * @param fax
     * @param email
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "EditPerson", action = "http://streamline/EditPerson")
    @WebResult(name = "EditPersonResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "EditPerson", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.EditPerson")
    @ResponseWrapper(localName = "EditPersonResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.EditPersonResponse")
    public ServiceQueryResultOfString editPerson(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "uid", targetNamespace = "http://streamline/")
                    String uid,
            @WebParam(name = "firstName", targetNamespace = "http://streamline/")
                    String firstName,
            @WebParam(name = "lastName", targetNamespace = "http://streamline/")
                    String lastName,
            @WebParam(name = "company", targetNamespace = "http://streamline/")
                    String company,
            @WebParam(name = "position", targetNamespace = "http://streamline/")
                    String position,
            @WebParam(name = "notes", targetNamespace = "http://streamline/")
                    String notes,
            @WebParam(name = "businessPhone", targetNamespace = "http://streamline/")
                    String businessPhone,
            @WebParam(name = "mobilePhone", targetNamespace = "http://streamline/")
                    String mobilePhone,
            @WebParam(name = "fax", targetNamespace = "http://streamline/")
                    String fax,
            @WebParam(name = "email", targetNamespace = "http://streamline/")
                    String email,
            @WebParam(name = "photoBase64", targetNamespace = "http://streamline/")
                    String photoBase64,
            @WebParam(name = "allowLogin", targetNamespace = "http://streamline/")
                    boolean allowLogin);

    /**
     *
     * @param aspnetSessionId
     * @param personId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "CheckUserPhoto", action = "http://streamline/CheckUserPhoto")
    @WebResult(name = "CheckUserPhotoResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "CheckUserPhoto", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.CheckUserPhoto")
    @ResponseWrapper(localName = "CheckUserPhotoResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.CheckUserPhotoResponse")
    public ServiceQueryResultOfString checkUserPhoto(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "personId", targetNamespace = "http://streamline/")
                    String personId);

    /**
     *
     * @param aDid
     * @param aspnetSessionId
     * @param personId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "LinkUserToAD", action = "http://streamline/LinkUserToAD")
    @WebResult(name = "LinkUserToADResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "LinkUserToAD", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.LinkUserToAD")
    @ResponseWrapper(localName = "LinkUserToADResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.LinkUserToADResponse")
    public ServiceQueryResultOfString linkUserToAD(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "personId", targetNamespace = "http://streamline/")
                    String personId,
            @WebParam(name = "ADid", targetNamespace = "http://streamline/")
                    String aDid);

    /**
     *
     * @param aspnetSessionId
     * @param personId
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.persons.ServiceQueryResultOfString
     */
    @WebMethod(operationName = "DeleteLinkWithAD", action = "http://streamline/DeleteLinkWithAD")
    @WebResult(name = "DeleteLinkWithADResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "DeleteLinkWithAD", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.DeleteLinkWithAD")
    @ResponseWrapper(localName = "DeleteLinkWithADResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.persons.DeleteLinkWithADResponse")
    public ServiceQueryResultOfString deleteLinkWithAD(
            @WebParam(name = "ASPNETSessionId", targetNamespace = "http://streamline/")
                    String aspnetSessionId,
            @WebParam(name = "personId", targetNamespace = "http://streamline/")
                    String personId);

}
