
package ru.rbt.jetski.advanta.ws.login;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Login", targetNamespace = "http://streamline/", wsdlLocation = "https://rbtn.a2nta.ru/components/services/login.asmx?WSDL")
public class Login_Service
    extends Service
{

    private final static URL LOGIN_WSDL_LOCATION;
    private final static WebServiceException LOGIN_EXCEPTION;
    private final static QName LOGIN_QNAME = new QName("http://streamline/", "Login");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://rbtn.a2nta.ru/components/services/login.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGIN_WSDL_LOCATION = url;
        LOGIN_EXCEPTION = e;
    }

    public Login_Service() {
        super(__getWsdlLocation(), LOGIN_QNAME);
    }

    public Login_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGIN_QNAME, features);
    }

    public Login_Service(URL wsdlLocation) {
        super(wsdlLocation, LOGIN_QNAME);
    }

    public Login_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGIN_QNAME, features);
    }

    public Login_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Login_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginSoap
     */
    @WebEndpoint(name = "LoginSoap")
    public LoginSoap getLoginSoap() {
        return super.getPort(new QName("http://streamline/", "LoginSoap"), LoginSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginSoap
     */
    @WebEndpoint(name = "LoginSoap")
    public LoginSoap getLoginSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://streamline/", "LoginSoap"), LoginSoap.class, features);
    }

    /**
     *
     * @return
     *     returns LoginSoap
     */
    @WebEndpoint(name = "LoginSoap12")
    public LoginSoap getLoginSoap12() {
        return super.getPort(new QName("http://streamline/", "LoginSoap12"), LoginSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginSoap
     */
    @WebEndpoint(name = "LoginSoap12")
    public LoginSoap getLoginSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://streamline/", "LoginSoap12"), LoginSoap.class, features);
    }

    /**
     *
     * @return
     *     returns LoginHttpPost
     */
    @WebEndpoint(name = "LoginHttpPost")
    public LoginHttpPost getLoginHttpPost() {
        return super.getPort(new QName("http://streamline/", "LoginHttpPost"), LoginHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginHttpPost
     */
    @WebEndpoint(name = "LoginHttpPost")
    public LoginHttpPost getLoginHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://streamline/", "LoginHttpPost"), LoginHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGIN_EXCEPTION!= null) {
            throw LOGIN_EXCEPTION;
        }
        return LOGIN_WSDL_LOCATION;
    }

}
