
package ru.rbt.jetski.advanta.ws.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginHttpPost", targetNamespace = "http://streamline/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginHttpPost {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://streamline/", partName = "Body")
    public String login(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "login")
                    String login,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password")
                    String password);

    /**
     *
     * @param password
     * @param login
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.login.AuthenticationResponse
     */
    @WebMethod(operationName = "Authenticate")
    @WebResult(name = "AuthenticationResponse", targetNamespace = "http://streamline/", partName = "Body")
    public AuthenticationResponse authenticate(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "login")
                    String login,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password")
                    String password);

    /**
     *
     * @param credentialID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataKey")
    @WebResult(name = "string", targetNamespace = "http://streamline/", partName = "Body")
    public String getDataKey(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "credentialID")
                    String credentialID);

    /**
     *
     * @param dataKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IssueLoginUrl")
    @WebResult(name = "string", targetNamespace = "http://streamline/", partName = "Body")
    public String issueLoginUrl(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dataKey")
                    String dataKey);

    /**
     *
     * @param credentialID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PersonalIndicators")
    @WebResult(name = "string", targetNamespace = "http://streamline/", partName = "Body")
    public String personalIndicators(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "credentialID")
                    String credentialID);

}
