
package ru.rbt.jetski.advanta.ws.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginSoap", targetNamespace = "http://streamline/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginSoap {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://streamline/login")
    @WebResult(name = "loginResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "login", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.LoginResponse")
    public String login(
            @WebParam(name = "login", targetNamespace = "http://streamline/")
                    String login,
            @WebParam(name = "password", targetNamespace = "http://streamline/")
                    String password);

    /**
     *
     * @param password
     * @param login
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.login.AuthenticationResponse
     */
    @WebMethod(operationName = "Authenticate", action = "http://streamline/Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.AuthenticateResponse")
    public AuthenticationResponse authenticate(
            @WebParam(name = "login", targetNamespace = "http://streamline/")
                    String login,
            @WebParam(name = "password", targetNamespace = "http://streamline/")
                    String password);

    /**
     *
     * @param cr
     * @return
     *     returns ru.rbt.ru.rbt.jetski.advanta.ws.login.CredentialInfo
     */
    @WebMethod(operationName = "IssueCredential", action = "http://streamline/IssueCredential")
    @WebResult(name = "IssueCredentialResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "IssueCredential", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.IssueCredential")
    @ResponseWrapper(localName = "IssueCredentialResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.IssueCredentialResponse")
    public CredentialInfo issueCredential(
            @WebParam(name = "cr", targetNamespace = "http://streamline/")
                    CredentialRequest cr);

    /**
     *
     * @param credentialID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataKey", action = "http://streamline/GetDataKey")
    @WebResult(name = "GetDataKeyResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "GetDataKey", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.GetDataKey")
    @ResponseWrapper(localName = "GetDataKeyResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.GetDataKeyResponse")
    public String getDataKey(
            @WebParam(name = "credentialID", targetNamespace = "http://streamline/")
                    String credentialID);

    /**
     *
     * @param dataKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IssueLoginUrl", action = "http://streamline/IssueLoginUrl")
    @WebResult(name = "IssueLoginUrlResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "IssueLoginUrl", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.IssueLoginUrl")
    @ResponseWrapper(localName = "IssueLoginUrlResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.IssueLoginUrlResponse")
    public String issueLoginUrl(
            @WebParam(name = "dataKey", targetNamespace = "http://streamline/")
                    String dataKey);

    /**
     *
     * @param credentialID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PersonalIndicators", action = "http://streamline/PersonalIndicators")
    @WebResult(name = "PersonalIndicatorsResult", targetNamespace = "http://streamline/")
    @RequestWrapper(localName = "PersonalIndicators", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.PersonalIndicators")
    @ResponseWrapper(localName = "PersonalIndicatorsResponse", targetNamespace = "http://streamline/", className = "ru.rbt.ru.rbt.jetski.advanta.ws.login.PersonalIndicatorsResponse")
    public String personalIndicators(
            @WebParam(name = "credentialID", targetNamespace = "http://streamline/")
                    String credentialID);

}
